version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install --upgrade pip
      - run: . .venv/bin/activate && pip install requests
      - run: . .venv/bin/activate && python -m unittest -v GitHubApi567-Hw4a/test_hw4a.py

workflows:
  build_and_test:
    jobs:
      - test
